Add events_and_payments.py, with a new list_events() function.
OpenTASS/OpenTASS pull request #5
Opened 2024-05-16 06:12 UTC by MrPiggy105

This adds a new file with a new function. Most of the code is similar to the other files, but this required a LOT of filtering of the site_data df columns. Also removed flake8 config as setup.cfg works just as well for me and better for others.

2024-05-16 06:37 UTC, Capta1nT0ad commented
Ideally keep commit messages to 52 chars or less next time. I will review the code.

2024-05-21 23:57 UTC, MrPiggy105 commented
Ready for review/merge => main. I will deal with attachments later. @Capta1nT0ad 

(not trying to be pushy btw, take your time)

2024-05-24 00:21 UTC, Capta1nT0ad commented on src/opentass/events_and_payments.py
> +    df = df.drop("link_url", errors="ignore")
Keep this.

2024-05-24 00:22 UTC, Capta1nT0ad commented on src/opentass/events_and_payments.py
> +    df = df.drop("sex", errors="ignore")  # don't even think about it-
Really!?

2024-05-24 00:23 UTC, Capta1nT0ad requested changes
Please address the couple of things I mentioned.

2024-05-24 00:23 UTC, Capta1nT0ad commented on src/opentass/events_and_payments.py
> +    df = df.drop("id", errors="ignore")
Keep this.

2024-05-24 01:50 UTC, MrPiggy105 commented
Fixed requested changes.

2024-05-24 02:03 UTC, MrPiggy105 commented
Fully fixed now!!

2024-05-24 02:11 UTC, MrPiggy105 reviewed
Fully done now!

2024-05-25 03:36 UTC, Capta1nT0ad requested changes
Just one more change and this one is ready for merge.

2024-05-25 03:36 UTC, Capta1nT0ad commented on src/opentass/events_and_payments.py
> +    df = df.T.drop("paid_flg", errors="ignore")
Please keep this one, then ready for merge.

2024-05-27 03:58 UTC, Capta1nT0ad commented
@MrPiggy105 Please review the changes I have requested, then this will be ready to merge.

2024-05-28 23:08 UTC, Capta1nT0ad commented
Please fix so I can merge @MrPiggy105.

2024-05-29 07:50 UTC, MrPiggy105 reviewed
Done! Ready for merge, can you have a look at my comment on the other PR review? Sorry it took so long for such a short thing

2024-05-29 11:24 UTC, Capta1nT0ad commented
@MrPiggy105 It appears that you have not committed your changes.

2024-05-29 11:27 UTC, MrPiggy105 commented
Whoops... pushed now.

2024-05-29 11:31 UTC, Capta1nT0ad commented
Thank you! please now review the other pr.

2024-05-29 11:31 UTC, merged